---
- name: Transfer and execute a script.
  hosts: ops-ipss
  remote_user: mhyde
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=test.sh dest=/tmp mode=0777

     - name: Execute the script
       command: sh /tmp/test.sh
